version: 0.2
phases:
  build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 240634792145.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t hello-repository .
      - docker tag hello-repository:latest 240634792145.dkr.ecr.us-east-1.amazonaws.com/hello-repository:latest
      - docker tag hello-repository:latest $ECR_IMAGE_URL:$(git rev-parse HEAD)
      - docker push $ECR_IMAGE_URL:latest
      - docker push $ECR_IMAGE_URL:$(git rev-parse HEAD)
